import test from 'node:test';
import assert from 'node:assert/strict';
import {loadBootstrap} from '../lib/bootstrap.ts';
import {publicAuthConfig} from '../lib/supabase/config.ts';

test('a healthy profile loads without an extra session request',async()=>{const paths=[];const result=await loadBootstrap(async path=>{paths.push(path);return Response.json({me:{id:'account-1',name:'Traveler'},records:[]})});assert.equal(result.available,true);assert.equal(result.authUser.id,'account-1');assert.deepEqual(paths,['/api/universe']);});
test('database failure preserves a separately verified signed-in account',async()=>{const paths=[];const result=await loadBootstrap(async path=>{paths.push(path);return path==='/api/auth/session'?Response.json({user:{id:'account-1',name:'Traveler'}}):Response.json({error:'Database unavailable'},{status:503})});assert.equal(result.available,false);assert.equal(result.payload,null);assert.equal(result.authUser.id,'account-1');assert.deepEqual(paths,['/api/universe','/api/auth/session']);});
test('a database error does not turn an anonymous visitor into a member',async()=>{const result=await loadBootstrap(async path=>path==='/api/auth/session'?Response.json({user:null}):Response.json({error:'Unavailable'},{status:503}));assert.equal(result.authUser,null);});
test('an unavailable identity service is never treated as verified identity',async()=>{const result=await loadBootstrap(async()=>Response.json({error:'Unavailable'},{status:503}));assert.equal(result.authUser,null);});
test('Vercel Supabase integration key names are supported without exposing secrets',()=>{const names=['NEXT_PUBLIC_SUPABASE_URL','SUPABASE_URL','NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY','NEXT_PUBLIC_SUPABASE_ANON_KEY','SUPABASE_PUBLISHABLE_KEY'];const before=Object.fromEntries(names.map(name=>[name,process.env[name]]));try{for(const name of names)delete process.env[name];process.env.SUPABASE_URL='https://test-project.supabase.co';process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY='sb_publishable_test-only';assert.equal(publicAuthConfig().configured,true);process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY='sb_secret_test-only';assert.equal(publicAuthConfig().configured,false);assert.equal(publicAuthConfig().key,'');process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY='eyJhbGciOiJIUzI1NiJ9.'+Buffer.from(JSON.stringify({role:'service_role'})).toString('base64url')+'.test';assert.equal(publicAuthConfig().configured,false);assert.equal(publicAuthConfig().key,'');}finally{for(const name of names){if(before[name]===undefined)delete process.env[name];else process.env[name]=before[name];}}});
