import {db,seed,viewer,unpack,access,getRecord,clean,error,rate,sameOrigin,insert,quiz,limitedBody,ownedImage} from '@/lib/server';
import {anime} from '@/lib/catalog';
import {z} from 'zod';
import {storage} from '@/lib/storage';
export const runtime='nodejs';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{await seed();const me=await viewer();const uid=me?.id||'';const d=db();const rows=(await d.prepare('SELECT * FROM records ORDER BY created DESC LIMIT 1500').all<any>()).results;const visible=[];const settingsFor=(id:string)=>{const r=rows.find(r=>r.owner===id&&r.kind==='settings');return r?JSON.parse(r.data):{}};const blocked=(id:string)=>rows.some(r=>r.kind==='block'&&(r.owner===uid&&r.target===id||r.owner===id&&r.target===uid));for(const r of rows){if(r.owner!==uid&&blocked(r.owner))continue;if(r.kind==='list'&&r.owner!==uid&&(settingsFor(r.owner).hideActivity||settingsFor(r.owner).privateProfile))continue;if(r.kind==='settings'&&r.owner!==uid)continue;if(r.kind==='report'&&me?.role!=='admin'&&r.owner!==uid)continue;if(r.kind==='notification'&&r.owner!==uid)continue;if((r.kind==='report'&&me?.role==='admin')||await access(r,uid)||(r.kind==='room'&&r.id===new URL(req.url).searchParams.get('room')&&JSON.parse(r.data).inviteToken&&JSON.parse(r.data).inviteToken===new URL(req.url).searchParams.get('invite'))){const item=unpack(r);visible.push(item);}}
const people=(await d.prepare('SELECT id,name,username,bio,avatar,banner,role,xp,status FROM profiles LIMIT 200').all<any>()).results;const safePeople=people.filter(p=>!rows.some(r=>r.owner===p.id&&r.kind==='settings'&&JSON.parse(r.data).privateProfile)&&p.role!=='demo'||p.role==='demo'||p.id===uid);
return Response.json({me,people:safePeople,records:visible,anime,quiz:quiz.map(({answer,...q})=>q)}, {headers:{'Cache-Control':'no-store'}});}catch(e){return error(e,503)}}
export async function POST(req:Request){try{sameOrigin(req);const me=await viewer();if(!me)return Response.json({error:'Sign in to make this universe yours.'},{status:401});await rate(me.id);if(Number(req.headers.get('content-length')||0)>25000)throw Error('This post is too large.');const raw:any=JSON.parse(new TextDecoder().decode(await limitedBody(req,25000))); if(JSON.stringify(raw).length>25000)throw Error('This request is too large.'); const b:any=z.object({action:z.string().max(30)}).passthrough().parse(raw);const d=db();let id='';
if(b.action==='profile'){const name=clean(b.name,50),username=clean(b.username,30).toLowerCase();if(!name||!/^[-a-z0-9_]{3,30}$/.test(username))throw Error('Use a name and a username with 3–30 letters, numbers, underscores or hyphens.');for(const field of ['avatar','banner'])if(b[field]&&!/^\/api\/media\/[a-zA-Z0-9-]+$/.test(b[field]))throw Error('Choose an uploaded image.');await ownedImage(me.id,b.avatar||'');await ownedImage(me.id,b.banner||'');await d.prepare('UPDATE profiles SET name=?,username=?,bio=?,status=?,avatar=?,banner=? WHERE id=?').bind(name,username,clean(b.bio,500),['Online','Away','Watching Anime','Gaming','Do Not Disturb','Offline'].includes(b.status)?b.status:'Online',b.avatar||null,b.banner||null,me.id).run();}
else if(b.action==='settings'){id='settings:'+me.id;const current=await getRecord(id);const payload={...(current?JSON.parse(current.data):{}),...b.data};if(JSON.stringify(payload).length>15000)throw Error('Theme code is too large.');await d.prepare('INSERT INTO records(id,owner,kind,target,visibility,data,created,updated) VALUES(?,?,?,? ,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated=excluded.updated').bind(id,me.id,'settings','','private',JSON.stringify(payload),Date.now(),Date.now()).run();}
else if(b.action==='list'){if(!anime.some(a=>a.id===b.target))throw Error('Anime not found.');if(!['Watching','Completed','Plan to Watch','On Hold','Dropped','Remove'].includes(b.status))throw Error('Choose a list status.');id='list:'+me.id+':'+b.target;if(b.status==='Remove')await d.prepare('DELETE FROM records WHERE id=? AND owner=?').bind(id,me.id).run();else {const score=Math.max(0,Math.min(10,Number(b.score)||0));const episodes=Math.max(0,Math.min(anime.find(a=>a.id===b.target)!.episodes,Number(b.episodes)||0));await d.prepare('INSERT INTO records(id,owner,kind,target,visibility,data,created,updated) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated=excluded.updated').bind(id,me.id,'list',b.target,'public',JSON.stringify({status:b.status,score,episodes,notes:clean(b.notes,1000),favorite:!!b.favorite}),Date.now(),Date.now()).run();}}
else if(b.action==='toggle'){if(!['reaction','save','membership','follow','vote','block'].includes(b.kind))throw Error('Unknown action.');const target=await getRecord(b.target);if(b.kind==='membership'){if(!target||!['community','room','chat'].includes(target.kind))throw Error('Space not found.');if(target.visibility==='private'&&!await access(target,me.id))throw Error('This space is invitation only.');}else if(b.kind==='follow'||b.kind==='block'){if(!await d.prepare('SELECT id FROM profiles WHERE id=?').bind(b.target).first())throw Error('Traveler not found.');}else if(!target||!await access(target,me.id))throw Error('Content not found.');id=b.kind+':'+me.id+':'+b.target;const existing=await getRecord(id);if(existing)await d.prepare('DELETE FROM records WHERE id=? AND owner=?').bind(id,me.id).run();else await insert(me.id,b.kind,{value:clean(b.value,50)},b.target,['save','block'].includes(b.kind)?'private':'public',id);}
else if(b.action==='create'){const allowed=['post','comment','idea','collection','community','room','chat','message','review','report','notification','invite'];if(!allowed.includes(b.kind))throw Error('Unknown content type.');if(b.kind==='notification')throw Error('Notifications are created by your activity.');const data={...b.data};const title=clean(data.title||data.name,150);const body=clean(data.body,8000);if(!title&&!body)throw Error('Write something first.');if(!['public','private'].includes(b.visibility||'public'))throw Error('Choose a visibility.');if(data.image&&!/^\/api\/media\/[a-zA-Z0-9-]+$/.test(data.image))throw Error('Choose an uploaded image.');if(data.image)await ownedImage(me.id,data.image);if(data.link){const u=new URL(data.link);if(!['https:','http:'].includes(u.protocol))throw Error('Use an http or https link.');data.link=u.href;}
let visibility=b.visibility||'public';const targetId=clean(b.target,150);if(['comment','message','review'].includes(b.kind)){if(b.kind==='review'){if(!anime.some(a=>a.id===targetId))throw Error('Anime not found.');}else{const target=await getRecord(targetId);if(!target||!await access(target,me.id))throw Error('You cannot post in this space.');if(b.kind==='message'){if(!['room','community','chat'].includes(target.kind))throw Error('Choose a chat room.');if(target.owner!==me.id&&!await d.prepare("SELECT id FROM records WHERE owner=? AND kind='membership' AND target=?").bind(me.id,target.id).first())throw Error('Join this space before sending a message.');}visibility=target.visibility;}}
if(b.kind==='report')visibility='private';if(b.kind==='chat')visibility='private';if(data.options){if(!Array.isArray(data.options)||data.options.length<2||data.options.length>6)throw Error('Add 2–6 poll options.');data.options=data.options.map((o:any)=>clean(o,100));}if(b.kind==='collection'){data.items=Array.isArray(data.items)?data.items.filter((x:any)=>anime.some(a=>a.id===x)).slice(0,100):[];}
if(b.kind==='room'){data.source='';if(visibility==='private')data.inviteToken=crypto.randomUUID();data.playing=false;data.time=0;data.tile=Number(data.tile)||0;data.host=me.name;}
id=await insert(me.id,b.kind,{...data,title,body,author:me.name},targetId,visibility);if(['room','chat','community'].includes(b.kind))await insert(me.id,'membership',{},id,'public','membership:'+me.id+':'+id);
if(b.kind==='chat'&&Array.isArray(data.members))for(const member of data.members.slice(0,20)){const p=await d.prepare("SELECT id FROM profiles WHERE id=? AND role!='demo'").bind(member).first();const preferences=await getRecord('settings:'+member);const blocked=await d.prepare("SELECT id FROM records WHERE kind='block' AND ((owner=? AND target=?) OR (owner=? AND target=?))").bind(me.id,member,member,me.id).first();if(p&&member!==me.id&&!blocked&&!(preferences&&JSON.parse(preferences.data).disableInvites))await insert(member,'membership',{},id,'public','membership:'+member+':'+id);}
if(b.kind==='comment'){const parent=await getRecord(targetId);const preferences=parent?await getRecord('settings:'+parent.owner):null;if(parent&&parent.owner!==me.id&&!parent.owner.startsWith('demo:')&&!(preferences&&JSON.parse(preferences.data).muteReplies))await insert(parent.owner,'notification',{title:me.name+' replied to your post',target:targetId},'','private');}
if(['post','review','idea'].includes(b.kind)){const recent=await d.prepare('SELECT COUNT(*) AS n FROM records WHERE owner=? AND kind=? AND created>?').bind(me.id,b.kind,Date.now()-86400000).first<any>();if(recent.n<=3)await d.prepare('UPDATE profiles SET xp=xp+10 WHERE id=?').bind(me.id).run();}}
else if(b.action==='update'){const r=await getRecord(b.id);if(!r||r.owner!==me.id)throw Error('Only the creator can edit this.');if(!['message','collection','room'].includes(r.kind))throw Error('This content cannot be edited here.');const allowed=r.kind==='message'?['body']:r.kind==='collection'?['items']:['source','playing','time'];const changes=Object.fromEntries(Object.entries(b.data||{}).filter(([k])=>allowed.includes(k)));if(r.kind==='message')changes.body=clean(changes.body,4000);const data={...JSON.parse(r.data),...changes};if(['room'].includes(r.kind)){if(data.source){const u=new URL(data.source);if(u.protocol!=='https:')throw Error('Use a secure, permitted media URL.');data.source=u.href;}data.time=Math.max(0,Math.min(86400,Number(data.time)||0));data.syncedAt=Date.now();}if(r.kind==='collection'){data.items=Array.isArray(data.items)?data.items.filter((x:any)=>anime.some(a=>a.id===x)).slice(0,100):[];}await d.prepare('UPDATE records SET data=?,updated=? WHERE id=? AND owner=?').bind(JSON.stringify(data),Date.now(),r.id,me.id).run();}
else if(b.action==='delete'){const r=await getRecord(b.id);if(!r||r.owner!==me.id&&me.role!=='admin')throw Error('You cannot remove this content.');await d.batch([d.prepare('DELETE FROM records WHERE id=?').bind(r.id),d.prepare('DELETE FROM records WHERE target=?').bind(r.id)]);}
else if(b.action==='quiz'){if(!Array.isArray(b.answers)||b.answers.length!==5||b.answers.some((n:any)=>!Number.isInteger(n)||n<0||n>3))throw Error('Answer all five questions.');const key='quiz:'+me.id+':'+new Date().toISOString().slice(0,10);const score=quiz.filter((q,i)=>q.answer===b.answers[i]).length;const before=await getRecord(key);if(!before){await d.batch([d.prepare('INSERT INTO records(id,owner,kind,target,visibility,data,created,updated) VALUES(?,?,?,?,?,?,?,?)').bind(key,me.id,'score','','public',JSON.stringify({score,total:5,game:'Daily Trivia',xp:score*10}),Date.now(),Date.now()),d.prepare('UPDATE profiles SET xp=xp+? WHERE id=?').bind(score*10,me.id)]);if(score===5)await insert(me.id,'achievement',{name:'Trivia Master',description:'A perfect daily quiz.'},'','public');}return Response.json({score,xp:before?0:score*10,alreadyPlayed:!!before,answers:quiz.map(q=>q.answer)});}
else if(b.action==='joinRoom'){const room=await getRecord(b.id);if(!room||room.kind!=='room')throw Error('Room not found.');if(room.visibility!=='public'&&room.owner!==me.id&&JSON.parse(room.data).inviteToken!==b.token&&!await access(room,me.id))throw Error('A valid invite is required.');id='membership:'+me.id+':'+room.id;if(!await getRecord(id))await insert(me.id,'membership',{},room.id,'public',id);}
else if(b.action==='read'){await d.prepare("DELETE FROM records WHERE owner=? AND kind='notification'").bind(me.id).run();}
else if(b.action==='export'){const rows=(await d.prepare('SELECT * FROM records WHERE owner=?').bind(me.id).all()).results;return Response.json({profile:me,records:rows.map(unpack)});}
else if(b.action==='deleteAccount'){const assets=(await d.prepare('SELECT id FROM uploads WHERE owner=?').bind(me.id).all<any>()).results;const bucket=storage();if(bucket)for(const asset of assets)await bucket.delete(asset.id);await d.prepare("DELETE FROM records WHERE target=? OR target IN (SELECT id FROM records WHERE owner=?)").bind(me.id,me.id).run();await d.batch([d.prepare('DELETE FROM records WHERE owner=?').bind(me.id),d.prepare('DELETE FROM uploads WHERE owner=?').bind(me.id),d.prepare('DELETE FROM profiles WHERE id=?').bind(me.id)]);}
else throw Error('Unknown action.');return Response.json({ok:true,id});}catch(e:any){if(e.code==='23505'||e.message?.includes('UNIQUE constraint'))return error(Error('That username is taken. Try another.'));return error(e)}}



