'use client';
import {createContext,useContext,useEffect,useState,useCallback} from 'react';
import {toast} from 'sonner';
import {communities,posts,rooms} from './catalog';
const initialRecords=[...communities.map(data=>({id:data.id,kind:'community',owner:'demo:hana',target:'',data})),...posts.map(data=>({id:data.id,kind:'post',owner:'demo:hana',target:'',data})),...rooms.map(data=>({id:data.id,kind:'room',owner:'demo:hana',target:'',data}))];
const Context=createContext<any>(null);
export function UniverseProvider({children}:{children:React.ReactNode}){const [data,setData]=useState<any>({records:initialRecords,people:[],me:null,quiz:[]});const [loading,setLoading]=useState(true);const [offline,setOffline]=useState(false);const [page,setPage]=useState('Home');const [detail,setDetail]=useState<any>(null);const [create,setCreate]=useState('');const [search,setSearch]=useState(false);
const refresh=useCallback(async()=>{try{const r=await fetch('/api/universe'+location.search);const body:any=await r.json();if(!r.ok)throw Error(body.error);setData(body);setOffline(false);}catch{setOffline(true);}finally{setLoading(false);}},[]);
useEffect(()=>{void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh()},6000);return()=>clearInterval(timer)},[refresh]);
useEffect(()=>{const params=new URLSearchParams(location.search);for(const type of ['room','collection','post'])if(params.get(type))setDetail({type,id:params.get(type)});const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setSearch(x=>!x)}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[]);
async function mutate(body:any,notice=''){if(!data.me){toast('Sign in to make this universe yours.');location.href='/signin?return_to='+encodeURIComponent(location.pathname+location.search);return null;}try{const r=await fetch('/api/universe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value:any=await r.json();if(!r.ok)throw Error(value.error);if(body.action!=='deleteAccount')await refresh();if(notice)toast.success(notice);return value;}catch(e:any){toast.error(e.message);return null;}}
const mine=(kind:string,target?:string)=>data.records.find((r:any)=>r.owner===data.me?.id&&r.kind===kind&&(target===undefined||r.target===target));const settings=mine('settings')?.data||{};
useEffect(()=>{const palettes:any={'Anime Night':['#0e0e16','#9a7df1'],'Cyber Tokyo':['#10141c','#23bfc5'],'Sakura Dream':['#1d151d','#db88b2'],'Shonen Fire':['#1c1211','#ed805e'],'Ocean Blue':['#101923','#6bace2'],'Purple Galaxy':['#151020','#b490ed'],'Crimson Cloud':['#160f13','#db5c7c'],'Minimal Light':['#f3f3f8','#7563c8'],'Pure Dark':['#09090b','#b7b4c5'],'Retro Anime':['#181a26','#e6ba78']};const p=palettes[settings.theme||'Anime Night']||palettes['Anime Night'];const root=document.documentElement;const light=settings.theme==='Minimal Light';root.style.setProperty('--background',p[0]);root.style.setProperty('--primary',/^#[a-fA-F0-9]{6}$/.test(settings.color)?settings.color:p[1]);root.style.setProperty('--foreground',light?'#242236':'#ecebf5');root.style.setProperty('--card',light?'#ffffff':'#181821');root.style.setProperty('--sidebar',light?'#ececf4':'#12121b');root.style.setProperty('--hover',light?'#e5e0f3':'#222031');root.style.setProperty('--border',light?'#00000012':'#ffffff0d');root.style.setProperty('--muted',light?'#676174':'#9291a8');root.style.colorScheme=light?'light':'dark';root.style.fontSize=([16,18,20].includes(settings.fontSize)?settings.fontSize:16)+'px';root.dataset.motion=settings.motion===false?'reduced':'full';if(settings.background&&/^\/api\/media\//.test(settings.background)){document.body.style.backgroundImage=`linear-gradient(#0e0e16df,#0e0e16df),url('${settings.background}')`;document.body.style.backgroundAttachment='fixed';document.body.style.backgroundSize='cover';}else document.body.style.backgroundImage='none';},[settings]);
return <Context.Provider value={{...data,loading,offline,refresh,mutate,mine,settings,page,setPage,detail,setDetail,create,setCreate,search,setSearch}}>{children}</Context.Provider>}
export const useUniverse=()=>useContext(Context);
export async function upload(file:File){const data=new FormData();data.append('file',file);const r=await fetch('/api/uploads',{method:'POST',body:data});const b:any=await r.json();if(!r.ok)throw Error(b.error);return b.url;}
export async function share(type:string,id:string,token?:string){const u=new URL(location.origin);u.searchParams.set(type,id);if(token)u.searchParams.set("invite",token);try{await navigator.clipboard.writeText(u.href);toast.success('Link copied. Visitors need access to this private site.');}catch{toast(u.href)}return u.href;}
export function download(name:string,data:any){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}

