import 'server-only';
import {Pool,types,type PoolClient} from 'pg';
types.setTypeParser(20,value=>Number(value));
let pool:Pool|undefined;
function getPool(){if(pool)return pool;const connectionString=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.POSTGRES_PRISMA_URL;if(!connectionString)throw Error('The database is not configured.');const url=new URL(connectionString);for(const name of ['sslmode','sslcert','sslkey','sslrootcert'])url.searchParams.delete(name);pool=new Pool({connectionString:url.toString(),max:2,idleTimeoutMillis:10000,connectionTimeoutMillis:10000,ssl:{rejectUnauthorized:true,...(process.env.DATABASE_CA_CERT?{ca:process.env.DATABASE_CA_CERT.replace(/\\n/g,'\n')}:{})}});pool.on('error',()=>console.error('Database connection interrupted.'));return pool;}
import {toPostgres} from './sql';
class Statement{values:unknown[]=[];constructor(readonly query:string){}bind(...values:unknown[]){const bound=new Statement(this.query);bound.values=values;return bound;}async execute(client?:PoolClient){const q=toPostgres(this.query);if(q.count!==this.values.length)throw Error('Database parameter mismatch.');return (client||getPool()).query(q.text,this.values);}async first<T=any>():Promise<T|null>{return (await this.execute()).rows[0]||null;}async all<T=any>():Promise<{results:T[]}>{return {results:(await this.execute()).rows};}async run(){const r=await this.execute();return {success:true,meta:{changes:r.rowCount||0}};}}
const database={prepare:(query:string)=>new Statement(query),async batch(statements:Statement[]){const client=await getPool().connect();try{await client.query('BEGIN');const results=[];for(const statement of statements)results.push(await statement.execute(client));await client.query('COMMIT');return results;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}};
export function getDatabase(){if(!process.env.DATABASE_URL&&!process.env.POSTGRES_URL&&!process.env.POSTGRES_PRISMA_URL)throw Error('The database is not configured.');return database;}
