import {getDatabase} from '@/lib/database';
import {getAuthenticatedUser} from '@/lib/auth';
import {anime,communities,posts,rooms} from '@/lib/catalog';
export function db(){return getDatabase();}
export const unpack=(r:any)=>({...r,data:JSON.parse(r.data)});
export async function seed(){const d=db();if(await d.prepare('SELECT id FROM anime WHERE id=?').bind('a24').first())return;const now=Date.now();const rows=[['demo:hana','hana.exe'],['demo:kai','Kai'],['demo:mika','mika.chan']];await d.batch(rows.map(([id,name])=>d.prepare('INSERT OR IGNORE INTO profiles(id,name,username,role,created) VALUES(?,?,?,?,?)').bind(id,name,id.split(':')[1],'demo',now)));const seedRecords=[...communities.map(c=>({id:c.id,owner:'demo:hana',kind:'community',data:c})),...posts.map((p,i)=>({id:p.id,owner:rows[i][0],kind:'post',data:p})),...rooms.map((r,i)=>({id:r.id,owner:rows[i][0],kind:'room',data:r})),{id:'idea-demo',owner:'demo:hana',kind:'idea',data:{title:'What if the stars are memories we left behind?',body:'A theory about The Quiet Cosmos: every signal is a memory trying to return home. Looking for a writer to turn this into a short fan-inspired story.',tag:'Looking for writer',author:'hana.exe'}},{id:'collection-demo',owner:'demo:mika',kind:'collection',data:{title:'Worlds for a rainy evening',body:'Quiet adventures and stories that feel like a warm blanket.',items:['a3','a4','a9','a10']}},{id:'review-demo',owner:'demo:hana',kind:'review',data:{title:'A quiet masterpiece',body:'The Forest Remembers makes the smallest moments feel enormous. A beautiful imaginary story.',score:9,author:'hana.exe'}}];await d.batch([...anime.map(a=>d.prepare('INSERT OR IGNORE INTO anime(id,title,genre,year,rating,data) VALUES(?,?,?,?,?,?)').bind(a.id,a.title,a.genre,a.year,Math.round(a.rating*10),JSON.stringify(a))),...seedRecords.map(r=>d.prepare('INSERT OR IGNORE INTO records(id,owner,kind,target,visibility,data,created,updated) VALUES(?,?,?,?,?,?,?,?)').bind(r.id,r.owner,r.kind,r.id==='review-demo'?'a3':'','public',JSON.stringify(r.data),now,now))]);}
export async function viewer(){const u=await getAuthenticatedUser();if(!u)return null;const d=db();await d.prepare("INSERT OR IGNORE INTO profiles(id,name,username,role,created) SELECT ?,?,?,?,?").bind(u.userId,u.fullName||'New traveler','traveler_'+u.userId.replace(/[^a-zA-Z0-9]/g,'').slice(-12),u.email.toLowerCase()===process.env.ADMIN_EMAIL?.toLowerCase()?'admin':'member',Date.now()).run();return d.prepare('SELECT * FROM profiles WHERE id=?').bind(u.userId).first<any>();}
export async function getRecord(id:string){return db().prepare('SELECT * FROM records WHERE id=?').bind(id).first<any>();}
export async function access(r:any,uid:string){if(!r)return false;if(r.owner===uid||r.visibility==='public')return true;if(r.kind==='message'||r.kind==='chat'||r.kind==='room')return !!await db().prepare("SELECT id FROM records WHERE kind='membership' AND owner=? AND target=?").bind(uid,r.kind==='message'?r.target:r.id).first();return false;}
export function clean(value:any,max=2000){if(typeof value!=='string')return '';return value.trim().slice(0,max);}
export function error(e:any,status=400){console.error('Universe request:',e instanceof Error?e.message:e);return Response.json({error:status>=500?'Your universe is temporarily unavailable. Your draft is safe; try again.':e.message||'Could not complete that action.'},{status});}
export async function rate(uid:string){const window=Math.floor(Date.now()/60000);const key=uid+':'+window;const row=await db().prepare('INSERT INTO rate_limits(key,count,window_id) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=rate_limits.count+1 RETURNING count').bind(key,window).first<any>();if(row.count>60)throw Error('You’re moving quickly. Please wait a minute.');if(Math.random()<.01)await db().prepare('DELETE FROM rate_limits WHERE window_id<?').bind(window-2).run();}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&new URL(origin).origin!==new URL(req.url).origin)throw Error('Please submit from Yorumi.');}
export async function insert(owner:string,kind:string,data:any,target='',visibility='public',id=crypto.randomUUID()){const now=Date.now();await db().prepare('INSERT INTO records(id,owner,kind,target,visibility,data,created,updated) VALUES(?,?,?,?,?,?,?,?)').bind(id,owner,kind,target,visibility,JSON.stringify(data),now,now).run();return id;}
export const quiz=[{q:'What does “isekai” describe?',options:['Another world','A cooking story','A school club','A detective case'],answer:0},{q:'Which term means everyday-life stories?',options:['Mecha','Slice of life','Isekai','Space opera'],answer:1},{q:'What is a cour?',options:['An opening song','A studio','A broadcast season block','A character type'],answer:2},{q:'What does an animation storyboard plan?',options:['Only the soundtrack','Scene composition and sequence','Merchandise','Subtitles'],answer:1},{q:'Which Yorumi story features a galaxy train?',options:['Rain Song','Ember Pact','Glass Garden','Starfall Express'],answer:3}];

export async function limitedBody(req:Request,max:number){if(Number(req.headers.get('content-length')||0)>max)throw Error('This request is too large.');const reader=req.body?.getReader();if(!reader)return new Uint8Array();const parts:Uint8Array[]=[];let length=0;while(true){const {done,value}=await reader.read();if(done)break;length+=value.byteLength;if(length>max){await reader.cancel();throw Error('This request is too large.');}parts.push(value);}const bytes=new Uint8Array(length);let offset=0;for(const part of parts){bytes.set(part,offset);offset+=part.length;}return bytes;}
export async function ownedImage(uid:string,url:string){if(!url)return;if(!/^\/api\/media\/[a-zA-Z0-9-]+$/.test(url)||!await db().prepare('SELECT id FROM uploads WHERE id=? AND owner=?').bind(url.split('/').pop(),uid).first())throw Error('Choose an image you uploaded.');}


