import {existsSync,readFileSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {Pool} from 'pg';
import {createClient} from '@supabase/supabase-js';
if(existsSync('.env.local'))process.loadEnvFile('.env.local');
const connectionString=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.POSTGRES_PRISMA_URL;
if(!connectionString){console.log('Database not connected: compiling the app without running migrations.');process.exit(0);}
const url=new URL(connectionString);for(const name of ['sslmode','sslcert','sslkey','sslrootcert'])url.searchParams.delete(name);
const pool=new Pool({connectionString:url.toString(),max:1,ssl:{rejectUnauthorized:true,...(process.env.DATABASE_CA_CERT?{ca:process.env.DATABASE_CA_CERT.replace(/\\n/g,'\n')}:{})}});
const client=await pool.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(812464)');await client.query('CREATE TABLE IF NOT EXISTS yorumi_migrations(name text PRIMARY KEY,checksum text NOT NULL,applied_at timestamptz NOT NULL DEFAULT now())');await client.query('ALTER TABLE yorumi_migrations ENABLE ROW LEVEL SECURITY');await client.query('REVOKE ALL ON yorumi_migrations FROM anon,authenticated');for(const name of readdirSync('db/migrations').filter(n=>n.endsWith('.sql')).sort()){const sql=readFileSync('db/migrations/'+name,'utf8');const checksum=createHash('sha256').update(sql).digest('hex');const before=await client.query('SELECT checksum FROM yorumi_migrations WHERE name=$1',[name]);if(before.rows[0]){if(before.rows[0].checksum!==checksum)throw Error('Previously applied migration changed: '+name);continue;}await client.query(sql);await client.query('INSERT INTO yorumi_migrations(name,checksum) VALUES($1,$2)',[name,checksum]);console.log('Applied '+name);}await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();await pool.end();}
const storageUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL;const storageKey=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY;
if(storageUrl&&storageKey){const admin=createClient(storageUrl,storageKey,{auth:{persistSession:false}});const name=process.env.SUPABASE_STORAGE_BUCKET||'yorumi-media';const {data,error}=await admin.storage.getBucket(name);if(!data){const created=await admin.storage.createBucket(name,{public:false,fileSizeLimit:5*1024*1024,allowedMimeTypes:['image/png','image/jpeg','image/webp']});if(created.error)throw Error('Could not initialize private media storage.');}else if(data.public)throw Error('Yorumi media bucket must be private.');console.log('Private image storage is ready.');}
